name: codekidd_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.5
  http: ^1.1.0
  mask_text_input_formatter: ^2.5.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  video_player: ^2.8.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/brand/
    - assets/images/